// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ92xJH13tPXLNKoXNHEHDxZO9LHT-7qk',
    appId: '1:899648586843:web:732b04f732ce3c2f832b7e',
    messagingSenderId: '899648586843',
    projectId: 'flutter-login-exam',
    authDomain: 'flutter-login-exam.firebaseapp.com',
    storageBucket: 'flutter-login-exam.firebasestorage.app',
    measurementId: 'G-PGZ4C9CHEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSJGTZ1g1x5eR-UCzMsQ31U4KPcFjSMwA',
    appId: '1:899648586843:android:5e054b1ddf3828a7832b7e',
    messagingSenderId: '899648586843',
    projectId: 'flutter-login-exam',
    storageBucket: 'flutter-login-exam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiZIZj2z7gTOBKQfi7zVczgdzn13EZtYA',
    appId: '1:899648586843:ios:5435b7ef6a3befbf832b7e',
    messagingSenderId: '899648586843',
    projectId: 'flutter-login-exam',
    storageBucket: 'flutter-login-exam.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiZIZj2z7gTOBKQfi7zVczgdzn13EZtYA',
    appId: '1:899648586843:ios:5435b7ef6a3befbf832b7e',
    messagingSenderId: '899648586843',
    projectId: 'flutter-login-exam',
    storageBucket: 'flutter-login-exam.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ92xJH13tPXLNKoXNHEHDxZO9LHT-7qk',
    appId: '1:899648586843:web:93862f14b92a2f1c832b7e',
    messagingSenderId: '899648586843',
    projectId: 'flutter-login-exam',
    authDomain: 'flutter-login-exam.firebaseapp.com',
    storageBucket: 'flutter-login-exam.firebasestorage.app',
    measurementId: 'G-VHRPSZJS4G',
  );
}
